In [3]:
import pandas as pd
data = pd.read_csv('hp.csv', header=None)
data.rename(columns={0: 'who'}, inplace=True)
data.head(8)

   who    1    2    3    4    5    6    7    8    9   10
0    1    4   59  124   24   59   98    2   12   79   79
1    2  108   34   79   13   31   53   62   67  149  135
2    3   73  103    4  125   85   95    5   18  131   96
3    4   28  112  102   48  143   32  133   86   60   77
4    5   73  139   76   32  130  117    8   22   94  136
5    6   10    7  118   92   25   66   43  101  146  144
6    7  117  114  109  115  135   55   46   94   62   87
7    8   31  104   85  100   39   28   89   94  115   36

In [4]:
my_number = 148
for rank in range(1, 11):
    for i in data.where(data[rank] == my_number)['who']:
        if i > 0 and i < 200:
            print(rank, int(i), sep='\t')

1	14
1	42
2	47
2	91
5	127
6	133
8	10
8	128
8	130
10	56